spring.application.name=workflow

server.port=8081

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/workflow_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Connection Pool Configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000


# Enable second-level caching
hibernate.cache.use_second_level_cache=true
hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory

#Resilience4j Configuration
resilience4j.circuitbreaker.instances.auditLogProducer.register-health-indicator=true
resilience4j.circuitbreaker.instances.auditLogProducer.sliding-window-size=10
resilience4j.circuitbreaker.instances.auditLogProducer.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.auditLogProducer.wait-duration-in-open-state=10000
resilience4j.circuitbreaker.instances.auditLogProducer.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.auditLogProducer.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.auditLogProducer.initial-state=CLOSED


# Flyway Configuration
spring.flyway.enabled=false
spring.flyway.clean-on-migrate=false
spring.flyway.validate-on-migrate=true
spring.flyway.locations=classpath:db/migration

