create table `group` (created_at datetime(6), created_by bigint, id bigint not null auto_increment, updated_at datetime(6), updated_by bigint, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table notification_log (created_at datetime(6), created_by bigint, id bigint not null auto_increment, sent_at datetime(6), template_id bigint not null, updated_at datetime(6), updated_by bigint, user_id bigint not null, channel varchar(255), status varchar(255), primary key (id)) engine=InnoDB;
create table notification_template (created_at datetime(6), created_by bigint, id bigint not null auto_increment, updated_at datetime(6), updated_by bigint, body_template varchar(255), channel varchar(255), event_type varchar(255), subject_template varchar(255), primary key (id)) engine=InnoDB;
create table permission (created_at datetime(6), created_by bigint, id bigint not null auto_increment, updated_at datetime(6), updated_by bigint, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table role (created_at datetime(6), created_by bigint, id bigint not null auto_increment, updated_at datetime(6), updated_by bigint, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table role_permission (created_at datetime(6), created_by bigint, id bigint not null auto_increment, permission_id bigint not null, role_id bigint not null, updated_at datetime(6), updated_by bigint, primary key (id)) engine=InnoDB;
create table task_escalation_rule (escalation_time_mins integer, created_at datetime(6), created_by bigint, escalated_to_role_id bigint not null, id bigint not null auto_increment, step_id bigint not null, updated_at datetime(6), updated_by bigint, primary key (id)) engine=InnoDB;
create table user (created_at datetime(6), created_by bigint, id bigint not null auto_increment, updated_at datetime(6), updated_by bigint, email varchar(255), status varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table user_delegation (end_date date, start_date date, created_at datetime(6), created_by bigint, from_user_id bigint not null, id bigint not null auto_increment, to_user_id bigint not null, updated_at datetime(6), updated_by bigint, primary key (id)) engine=InnoDB;
create table user_dnd (end_time time(6), start_time time(6), created_at datetime(6), created_by bigint, id bigint not null auto_increment, updated_at datetime(6), updated_by bigint, user_id bigint not null, primary key (id)) engine=InnoDB;
create table user_group (created_at datetime(6), created_by bigint, group_id bigint not null, id bigint not null auto_increment, updated_at datetime(6), updated_by bigint, user_id bigint not null, primary key (id)) engine=InnoDB;
create table user_role (created_at datetime(6), created_by bigint, id bigint not null auto_increment, role_id bigint not null, updated_at datetime(6), updated_by bigint, user_id bigint not null, primary key (id)) engine=InnoDB;
create table workflow (created_at datetime(6), created_by bigint, id bigint not null auto_increment, updated_at datetime(6), updated_by bigint, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table workflow_attachment (created_at datetime(6), created_by bigint, id bigint not null auto_increment, task_id bigint not null, updated_at datetime(6), updated_by bigint, uploaded_at datetime(6), uploaded_by bigint not null, file_name varchar(255), file_url varchar(255), primary key (id)) engine=InnoDB;
create table workflow_auto_approval (auto_approve bit, created_at datetime(6), created_by bigint, id bigint not null auto_increment, step_id bigint not null, updated_at datetime(6), updated_by bigint, condition_field varchar(255), condition_value varchar(255), operator varchar(255), primary key (id)) engine=InnoDB;
create table workflow_builder_config (created_at datetime(6), created_by bigint, id bigint not null auto_increment, updated_at datetime(6), updated_by bigint, workflow_version_id bigint not null, json_config varchar(255), primary key (id)) engine=InnoDB;
create table workflow_comment (created_at datetime(6), created_by bigint, id bigint not null auto_increment, task_id bigint not null, updated_at datetime(6), updated_by bigint, user_id bigint not null, comment varchar(255), primary key (id)) engine=InnoDB;
create table workflow_condition (created_at datetime(6), created_by bigint, id bigint not null auto_increment, step_id bigint not null, target_step_id bigint, updated_at datetime(6), updated_by bigint, expected_value varchar(255), field_name varchar(255), operator varchar(255), primary key (id)) engine=InnoDB;
create table workflow_instance (created_at datetime(6), created_by bigint, entity_id bigint, id bigint not null auto_increment, updated_at datetime(6), updated_by bigint, workflow_version_id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table workflow_instance_step (created_at datetime(6), created_by bigint, ended_at datetime(6), id bigint not null auto_increment, instance_id bigint not null, started_at datetime(6), step_id bigint not null, updated_at datetime(6), updated_by bigint, status varchar(255), primary key (id)) engine=InnoDB;
create table workflow_rule (created_at datetime(6), created_by bigint, group_id bigint, id bigint not null auto_increment, role_id bigint, step_id bigint not null, updated_at datetime(6), updated_by bigint, user_id bigint, condition_json varchar(255), primary key (id)) engine=InnoDB;
create table workflow_sla (expected_completion_time_mins integer, notify_on_violation bit, created_at datetime(6), created_by bigint, id bigint not null auto_increment, step_id bigint not null, updated_at datetime(6), updated_by bigint, primary key (id)) engine=InnoDB;
create table workflow_step (is_mandatory bit, step_order integer, created_at datetime(6), created_by bigint, id bigint not null auto_increment, updated_at datetime(6), updated_by bigint, workflow_version_id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table workflow_task (assigned_to bigint not null, completed_at datetime(6), created_at datetime(6), created_by bigint, due_date datetime(6), id bigint not null auto_increment, step_instance_id bigint not null, updated_at datetime(6), updated_by bigint, status varchar(255), primary key (id)) engine=InnoDB;
create table workflow_task_type (created_at datetime(6), created_by bigint, id bigint not null auto_increment, step_id bigint not null, updated_at datetime(6), updated_by bigint, config varchar(255), task_type varchar(255), primary key (id)) engine=InnoDB;
create table workflow_version (is_active bit, created_at datetime(6), created_by bigint, id bigint not null auto_increment, updated_at datetime(6), updated_by bigint, workflow_id bigint not null, description varchar(255), version varchar(255), primary key (id)) engine=InnoDB;
alter table notification_log add constraint FK6bb6fh2mc8o0fk2ccrjxapjho foreign key (template_id) references notification_template (id);
alter table notification_log add constraint FKiw4vkt84rm11wouj9rslmqf5o foreign key (user_id) references user (id);
alter table role_permission add constraint FKf8yllw1ecvwqy3ehyxawqa1qp foreign key (permission_id) references permission (id);
alter table role_permission add constraint FKa6jx8n8xkesmjmv6jqug6bg68 foreign key (role_id) references role (id);
alter table task_escalation_rule add constraint FKfn0diu552mwcw36ukcc85s9wq foreign key (escalated_to_role_id) references role (id);
alter table task_escalation_rule add constraint FK1l83tae2coyryd1qp2d3n2xl0 foreign key (step_id) references workflow_step (id);
alter table user_delegation add constraint FKbco79flwnklhe7hc08js9nh8e foreign key (from_user_id) references user (id);
alter table user_delegation add constraint FK5ly08i7ww1fgqs49m7lsqak46 foreign key (to_user_id) references user (id);
alter table user_dnd add constraint FK6h8df6sv5m2g0kq888j9k7051 foreign key (user_id) references user (id);
alter table user_group add constraint FKjonf4pqux3h1e687sd18dhcnj foreign key (group_id) references group (id);
alter table user_group add constraint FK1c1dsw3q36679vaiqwvtv36a6 foreign key (user_id) references user (id);
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);
alter table workflow_attachment add constraint FKfku0ljs90psn2ajgmsyrvl6wo foreign key (task_id) references workflow_task (id);
alter table workflow_attachment add constraint FKdr5mis7wkeyavv5ah0wy4w9jw foreign key (uploaded_by) references user (id);
alter table workflow_auto_approval add constraint FK8m8be05rwgyijh98ly0evgq9b foreign key (step_id) references workflow_step (id);
alter table workflow_builder_config add constraint FKq7yp7cjwjsuegd7w2u06pxpl5 foreign key (workflow_version_id) references workflow_version (id);
alter table workflow_comment add constraint FKr6tpt3tp3rgip7pnfjyni1spn foreign key (task_id) references workflow_task (id);
alter table workflow_comment add constraint FKbnmq9c8m2grummgrsbmug0730 foreign key (user_id) references user (id);
alter table workflow_condition add constraint FKrp208j4tdrwy8fj83wx9l2s5w foreign key (step_id) references workflow_step (id);
alter table workflow_instance add constraint FKcglxct4a9ab6aeupit4he7s2b foreign key (workflow_version_id) references workflow_version (id);
alter table workflow_instance_step add constraint FK5g6bky1bl1cbemkkh0sl3grds foreign key (instance_id) references workflow_instance (id);
alter table workflow_instance_step add constraint FK5t19kvdhbedox1lcjymxohhbc foreign key (step_id) references workflow_step (id);
alter table workflow_rule add constraint FKjh9g4wdvu1hb2p5gix1i7i24m foreign key (step_id) references workflow_step (id);
alter table workflow_sla add constraint FKxnpbj2y01gulnc9rcgy1psbl foreign key (step_id) references workflow_step (id);
alter table workflow_step add constraint FKjr7cy20larqhuxnhkgt6bggkq foreign key (workflow_version_id) references workflow_version (id);
alter table workflow_task add constraint FKcw32p2sghscpnogm67uer7164 foreign key (assigned_to) references user (id);
alter table workflow_task add constraint FKr4h6itawhqix514jg03nan47h foreign key (step_instance_id) references workflow_instance_step (id);
alter table workflow_task_type add constraint FK6swdsb9qs1afma6o9j5tkn9r8 foreign key (step_id) references workflow_step (id);
alter table workflow_version add constraint FKgjhy6w5q8buydj1hboch9dxl5 foreign key (workflow_id) references workflow (id);
